script:
- docker build --target test --tag todo-app:test .
- docker run todo-app:test tests
- docker run -e MONGODB_USERNAME -e MONGODB_PASSWORD todo-app:test e2e_tests

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main

env:
  global:
  - DOCKER_USERNAME=charliecumber
  - secure: vXObwB6o3BOI97C+Ybeh18sl4TfuhIF9p063seDye69RmU1yGt8FH93IPI2rHlue/WkuuqOBFsBnn6rKopwEiS80yRs5ElB6Z2BDIT7gDTstZABaYzeM36ax0QWC0u/+nRN7Y88pnhLE6ULZVnN4/eKL+JWOIhvtRmuu7kBvBNUDEi3E1LsVvzjFL8hSTpkz8VsJjhkyifpffO0zq3gvYKxULkdx5yZSZ8BwS1Qgmng4/zJcVVc5IEZ5FITK8A98xLD0VFtlAjhUJF23PywnkhlTIsL+9pmgSyEAJA+gACgJpUKUy8JgB8xnPDeqP8pHd3/ejYTfjrALw/MNxaBjL89KDMMf/4Xr+2U9N2lZH50MRli8uj8s3942fl8w9FMv44PZSu32JXkHYhs0TF6Nektwn74Rbfc0zsJXov+hUBSF9tge86gNnqxU+QrgoxpuYtraymknEZW3dZJcGUftAS732EzkMPX+PjGJAm77NIotNKnNxTiEvX24kssTXrOng18o0yeGYpTYDD23qzEuiDerTklJbIS2U1AwC1uowfDZ7JVHlN+ZChOudiDDDk8sYuiI6lACc8KaFEdQGTFsN5lbGhGNK7dgZVhh2r1hYIpfVnIGbk2jCTLScDGUTBiCLw7LTRionVhjqPEOL7SW8CSBNXkYFBA13S1dILUGOgo=
  - secure: PN603L0ktOMMih53ol2bVjejcnJ/6kZwnEjPDszj+l0r2bb2LegLMDTdPcHhIoU8qq4fYktIRGF4LgXu+sFjFQdD/upqpcxcs0N9Op5ErUBnaFhik7zQLzKEdkTPY+xcFFjHg32ODFMGF8FkOXzEmm0425/ui9zl9g33cCZfYi27VfRnAtsukMjiwYtay5Q74DaZi6NelON9HkQvf1IXE4snP2ckPEiEAeacdQ35YQqNHXcKNBCXMz8oYKvlD62wLZWEGzhjhLAMcyHg5SDV73Vf6Uuds65DAPNIizp2Pn0RR86ofnIYUXo8+M7f3xKiNpN6F9FHD65mzIdXxGEh/OyO1LPFPX9E79tvjAZqnetIS4R3M4SqD7fNfsSx7HtseQE/un5b+qhiHCnGds28JCmYpFfKp2i/yMqy+ARqMQ03u4HIzIiPP6P72nDx0cNQePDF1/h6h7bnrL/BxV0npUcE9gcWLCQtNHfQdq0f6hTySrcX/kF24hw9Ev68hh+Z9vItpKXVtnkpPB72eckiN+L86W476quL13rDz2TmqWHaGsiXZuabN05t9L71eGVxdJ+VugADmkOpt+pyCL/lMp/9HrqhAKFxB+YRJHt3NYRX+st0eUVPDRXv3vicS/Gvgcfvf4fj2DeJweS2Hr1IuQlT/pVbyFd/CtFWYI/WfQ0=
