version: '3.8'
services: 
    todo-app:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        image: todo-app:prod
        ports:
            - "5000:5000"
        env_file: .env
